### PR TITLE
[#79] try to resolve RetroArchHosts first.

### LINKED ISSUE #79: Configuration `RetroArchHosts` should take hostname
Hi,

if I pass a host name to the config, retroarch will add an empty QHostAddress:

## how to reproduce

```ini
[General]
retroarchdevice=true
RetroArchHosts="remoteName=docker"
debugLog=true
```

## expected output

`2021-04-12T07:38:24           RA Factory - Debug: Trying to connect to New RetroArch "remoteName" QHostAddress("host.docker.internal")`

## actual output

`2021-04-12T07:38:24           RA Factory - Debug: Trying to connect to New RetroArch "remoteName" QHostAddress("")`

## problematic line

https://github.com/Skarsnik/QUsb2snes/blob/a4248c38d30745f0339c1cc854697cb6b95ba3bb/devices/retroarchfactory.cpp#L53-L59

Note: the assignment of a string to QHostAddress won’t work here as it expects an IP.

## suggested solution

I am not a C++ programmer, BUT according to the docs something like this (pseudocode) should work:

```cpp
QHostInfo info = QHostInfo::fromName(host.split('=').at(1));
QHostAddress address = info->addresses()[0];
newHost.addr = QHostAddress(address);
```

I think this should also work with IPs.

### PR DESCRIPTION
**Pull request by bmarwell**
- fixes #79

### CODE REVIEW

**Comment by Skarsnik** [comment]
Hm, this add blocking code when I am trying to remove most of it now x)

**Comment by bmarwell** [comment]
> Hm, this add blocking code when I am trying to remove most of it now x)

Well, what could be done is to resolve the host name ONCE and then use that the whole time. But I am not good enough at C++ to do this.

**Comment by Skarsnik** [comment]
Add a comment that QHostInfo::fromName is blocking so I remember to refactor it later when I will make the code fully async x)

**Comment by bmarwell** [comment]
Done, please re-review @Skarsnik

**Pull request merged**
